import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/Components/LenisProvider";
import { PreloaderProvider } from "@/Components/PreloaderProvider";
import CustomCursor from "@/Components//CustomCursor"; // Import the CustomCursor component



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CustomCursor /> 
        <PreloaderProvider>
          <LenisProvider>
            {/* Add global header or modals here if needed */}
            {children}
            {/* Add global footer here if needed */}
          </LenisProvider>
        </PreloaderProvider>
      </body>
    </html>
  );
}

