import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import SmoothScrollWrapper from "@/components/SmoothScrollWrapper";

// Set up DM Sans font with variable for CSS
const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["200", "300", "400", "500", "600", "700"],         // Choose weights as needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
        className={` antialiased`}
      >
         <SmoothScrollWrapper >{children}</SmoothScrollWrapper>
      </body>
    </html>
  );
}
