import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/Components/LenisProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
        className={` antialiased`}
      >
        
          <LenisProvider>
            {children}
          </LenisProvider>
        
      </body>
    </html>
  );
}
